version: '2'

services: 
  app: 
    build: .
    environment:
      - DB_USER=janlevent
      - DB_PWD=DigitalBoardroom2021
      - DB_URL=realtime-bi.tk
      - DB_NAME=realtimebi
    volumes: 
      - ./code:/usr/src/app/
    ports:
      - 30001:8404
    #To Start Container in Bash Mode:
    stdin_open: true
    tty: true
    container_name: digital-boardroom
    command: >
      bash -c "cd /usr/src/app/ && pip install -r requirements.txt && python"