apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-boardroom-server
  labels:
    app: digital-boardroom-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: digital-boardroom-server
  template:
    metadata:
      labels:
        app: digital-boardroom-server
    spec:
      containers:
      - name: digital-boardroom-server
        image: leventlukas/digital-boardroom:latest
        command: ["python", "server.py"]
        ports:
        - name: http
          containerPort: 8404
        env:
        - name: DB_USER
          value: janlevent
        - name: DB_PWD
          value: DigitalBoardroom2021
        - name: DB_URL
          value: realtime-bi.tk
        - name: DB_NAME
          value: realtimebi

---
apiVersion: v1
kind: Service
metadata:
  name: digital-boardroom-service
  labels:
    app: digital-boardroom-server
spec:
  type: NodePort
  selector:
    app: digital-boardroom-server
  ports:
    - protocol: TCP
      port: 8404
      targetPort: http
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-boardroom-loopclient
  labels:
    app: digital-boardroom-loopclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digital-boardroom-loopclient
  template:
    metadata:
      labels:
        app: digital-boardroom-loopclient
    spec:
      containers:
      - name: digital-boardroom-loopclient
        image: leventlukas/digital-boardroom:latest
        command: ["python", "execute.py", '5']
